language: node_js

cache: yarn

notifications:
  email: false

branches:
  only: 
    - master

node_js: 
  - '8'
  - '9'

before_script: yarn build-parser

script:
  - yarn test

jobs:
  include:
    - stage: release
      node_js: lts/*
      before_script: yarn build-parser
      script: yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release


